version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn run build
