version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn run build
      - add_ssh_keys:
          fingerprints:
            - "7a:19:fb:d7:aa:c6:fc:ea:a3:fc:bd:b9:84:d2:7a:46"
      - run:
          name: Send files to klve.nl
          command: |
            echo 'klve.nl ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmHJt/wfrkM4vItZ4BJLUNTVIUiUKCEUv5zlWCRmTebe7fgGHeWCioecD6qXXCA98WBeArs8/cgGZ5kb1HRrnF9UjX90CkgFgCTs6mKFtjk9D2GMFyczESVh4puhJFI8y5+apIrHqdaQfoVzqEt+lB/XGlSowIdOuH+0yxZ1yMeRB1KYpUDDTQyrShFAHfajQv6jOprGRkq+oQuUwfLcuz4Jp/43OfMgCTmXSIZSLhubEgtKMX6pVmrPmnpNvwlQ3beZwgCz6S/C06LRZvjvTTQiHEMzxrFBk34GRy+yLAAT5id7s2yY0OyNrnxcdgf+GnDve5NqWpggOaW5zQXRYT' >> ~/.ssh/known_hosts
            scp -rp build/* klve.nl:prime/klve.nl/public/
